// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@types+node@25.3.0_@vue+compiler-sfc@3.5.28_better-sql_589ae461961e03907851cb09e39d7cfe/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@types+node@25.3.0_@vue+compiler-sfc@3.5.28_better-sql_589ae461961e03907851cb09e39d7cfe/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@types+node@25.3.0_@vue+compiler-sfc@3.5.28_better-sql_589ae461961e03907851cb09e39d7cfe/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt-site-config@3.2.20_magicast@0.5.2_vite@7.3.1_@types+node@25.3.0_jiti@2.6.1_lightni_d4c7074aebaf0ee07f3ad39fff4fd1f3/node_modules/nuxt-site-config/dist/runtime/app/plugins/0.siteConfig.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@types+node@25.3.0_@vue+compiler-sfc@3.5.28_better-sql_589ae461961e03907851cb09e39d7cfe/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@types+node@25.3.0_@vue+compiler-sfc@3.5.28_better-sql_589ae461961e03907851cb09e39d7cfe/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@types+node@25.3.0_@vue+compiler-sfc@3.5.28_better-sql_589ae461961e03907851cb09e39d7cfe/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@types+node@25.3.0_@vue+compiler-sfc@3.5.28_better-sql_589ae461961e03907851cb09e39d7cfe/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@types+node@25.3.0_@vue+compiler-sfc@3.5.28_better-sql_589ae461961e03907851cb09e39d7cfe/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@types+node@25.3.0_@vue+compiler-sfc@3.5.28_better-sql_589ae461961e03907851cb09e39d7cfe/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.28_db0@0.3.4_better-sqlite3@12.6.2__eslint@10_dc8826004bb9c918c278f804c2736736/node_modules/@nuxtjs/i18n/dist/runtime/plugins/switch-locale-path-ssr.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.28_db0@0.3.4_better-sqlite3@12.6.2__eslint@10_dc8826004bb9c918c278f804c2736736/node_modules/@nuxtjs/i18n/dist/runtime/plugins/route-locale-detect.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.28_db0@0.3.4_better-sqlite3@12.6.2__eslint@10_dc8826004bb9c918c278f804c2736736/node_modules/@nuxtjs/i18n/dist/runtime/plugins/preload.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.28_db0@0.3.4_better-sqlite3@12.6.2__eslint@10_dc8826004bb9c918c278f804c2736736/node_modules/@nuxtjs/i18n/dist/runtime/plugins/dev.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.28_db0@0.3.4_better-sqlite3@12.6.2__eslint@10_dc8826004bb9c918c278f804c2736736/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt-og-image@5.1.13_@unhead+vue@2.1.4_vue@3.5.28_typescript@5.9.3___magicast@0.5.2_uns_99447b68fb59980461563e428c1f8348/node_modules/nuxt-og-image/dist/runtime/app/plugins/og-image-canonical-urls.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt-og-image@5.1.13_@unhead+vue@2.1.4_vue@3.5.28_typescript@5.9.3___magicast@0.5.2_uns_99447b68fb59980461563e428c1f8348/node_modules/nuxt-og-image/dist/runtime/app/plugins/route-rule-og-image.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+robots@5.7.0_magicast@0.5.2_vite@7.3.1_@types+node@25.3.0_jiti@2.6.1_lightningc_606c9efeaa19d2bad72f735440391338/node_modules/@nuxtjs/robots/dist/runtime/app/plugins/robot-meta.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt-site-config@3.2.20_magicast@0.5.2_vite@7.3.1_@types+node@25.3.0_jiti@2.6.1_lightni_d4c7074aebaf0ee07f3ad39fff4fd1f3/node_modules/nuxt-site-config/dist/runtime/app/plugins/i18n.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.4.0_@nuxt+content@3.11.2_better-sqlite3@12.6.2_magicast@0.5.2__@tiptap+exten_7cf97d5cd92157e2a3303af9218de1ab/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0.5.2_vite@7.3.1_@types+node@25.3.0_jiti@2.6.1_lightningcss@1_6c88b82260cf17c9aa940ee07babb042/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../app/plugins/i18n")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.3.1_@parcel+watcher@2.5.6_@types+node@25.3.0_@vue+compiler-sfc@3.5.28_better-sql_589ae461961e03907851cb09e39d7cfe/node_modules/nuxt/dist/pages/runtime/plugins/prerender.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.3_@vue+compiler-dom@3.5.28_db0@0.3.4_better-sqlite3@12.6.2__eslint@10_dc8826004bb9c918c278f804c2736736/node_modules/@nuxtjs/i18n/dist/runtime/plugins/ssg-detect.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt-site-config:init' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'i18n:plugin:switch-locale-path-ssr' | 'i18n:plugin:route-locale-detect' | 'i18n:plugin:preload' | 'i18n:dev' | 'i18n:plugin' | 'nuxt-site-config:i18n' | '@nuxt/icon' | 'i18n:plugin:ssg-detect'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
